Repository AndroidEarlyBirdy/EarlyBirdy, pull requests merged in 2023-10, with the labels that each got.

#1 feature : Fragment Binding 추가
  app/src/main/java/com/example/earlybirdy/board/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
Labels: Feature

#7 UI/main
  app/src/main/java/com/example/earlybirdy/MainActivity.kt
  app/src/main/java/com/example/earlybirdy/MainTabs.kt
  app/src/main/java/com/example/earlybirdy/MainViewPagerAdapter.kt
  app/src/main/java/com/example/earlybirdy/board/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/res/color/selector_tab.xml
  app/src/main/res/drawable/ic_background.xml
  app/src/main/res/drawable/ic_board.xml
  app/src/main/res/drawable/ic_board_fill.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_home_fill.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_mypage_fill.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Design

#9 Create Plan Activity Ui 작업 및 recyclerview 작업
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanAdapter.kt
  app/src/main/java/com/example/earlybirdy/data/Todo.kt
  app/src/main/res/drawable/ic_create_plan_add_todo.xml
  app/src/main/res/drawable/ic_create_plan_delete.xml
  app/src/main/res/drawable/item_todo.xml
  app/src/main/res/layout/activity_create_plan.xml
  app/src/main/res/layout/item_todo.xml
  gradle.properties
  settings.gradle
Labels: Design, Feature

#11 fix : AndroidManifest 변경 및 item layout 오류 fix
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_todo.xml
Labels: Fix

#12 Feature/UI 로그인 회원가입 UI 및 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/MainActivity.kt
  app/src/main/java/com/example/earlybirdy/board/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/dto/UserDto.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/drawable/bg_line.xml
  app/src/main/res/drawable/btn_sign_background.xml
  app/src/main/res/drawable/img_profile_add.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/values/style.xml
  build.gradle
Labels: Design, Feature

#14 fix: 로그인 회원가입 빈칸 에러 메시지 항목별 출력으로 수정
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
Labels: Fix

#17 feat: 앱 실행 시 로그인 회원가입 페이지에서 로그인 여부 체크 기능 추가
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/res/layout/activity_item_setting.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_todo.xml
Labels: Feature

#21 UI/profile
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/res/drawable/ic_profile_back.xml
  app/src/main/res/drawable/img_profile_camera.xml
  app/src/main/res/drawable/img_profile_eye.xml
  app/src/main/res/drawable/img_profile_openeye.xml
  app/src/main/res/drawable/img_profile_sample.png
  app/src/main/res/drawable/text_color_selector_profile.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/values/themes.xml
Labels: Design

#24 My Page Layout 구현, Main Activity 수정
  app/build.gradle
  app/src/main/res/drawable/bg_status.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: Design, Fix

#26 UI/splash
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/SplahActivity/SplashActivity.kt
  app/src/main/res/drawable/ic_earlybirdy.xml
  app/src/main/res/drawable/ic_earlybirdy_reverse.xml
  app/src/main/res/drawable/ic_logo.png
  app/src/main/res/layout/activity_splash.xml
Labels: Design

#28 Setting Activity 수정
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingAdapter.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingItem.kt
  app/src/main/res/drawable/btn_back.png
  app/src/main/res/drawable/btn_setting.xml
  app/src/main/res/drawable/ic_btn_back.xml
  app/src/main/res/layout/activity_item_setting.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/colors.xml
Labels: Fix

#30 MainActivity Refactor / Splash Activity Refactor
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/main/MainActivity.kt
  app/src/main/java/com/example/earlybirdy/main/MainTabs.kt
  app/src/main/java/com/example/earlybirdy/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/earlybirdy/main/SplashActivity.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_main.xml
Labels: Refactor

#32 Ui : BackGround Gradation layout 작업(fragment_my_page만)
  app/src/main/res/drawable/bg_gr3.png
  app/src/main/res/drawable/bg_status.xml
  app/src/main/res/drawable/ic_Insignia1.png
  app/src/main/res/drawable/ic_Insignia2.png
  app/src/main/res/drawable/ic_Insignia3.png
  app/src/main/res/drawable/ic_Insignia4.png
  app/src/main/res/drawable/ic_Insignia5.png
  app/src/main/res/layout/fragment_my_page.xml
Labels: Design

#34 UI : CreatePlanDialog, Feature: CreatePlanDialog
  app/build.gradle
  app/src/main/java/com/example/earlybirdy/board/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanDialog.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/drawable/dialog_edittext_background.xml
  app/src/main/res/drawable/dialog_radius_background.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_create_plan_dialog.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_board.xml
Labels: Design, Feature

#36 UI/home
  app/build.gradle
  app/src/main/res/drawable/btn_attend.xml
  app/src/main/res/drawable/btn_plus.xml
  app/src/main/res/drawable/circular_progress.xml
  app/src/main/res/drawable/ic_glass.xml
  app/src/main/res/drawable/ic_list_background.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_todo_main.xml
  app/src/main/res/values/style.xml
Labels: Design

#37 회원가입 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/dto/UserDto.kt
  app/src/main/java/com/example/earlybirdy/resetpassword/ResetPasswordActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
Labels: Feature

#41 feature/MyPageFragment
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragmentViewModel.kt
Labels: Feature

#46 CreatePlanActivity 달력 기능 구현
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanAdapter.kt
  app/src/main/java/com/example/earlybirdy/data/Todo.kt
Labels: Feature

#48 MyPage 달력 기능 구현
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/data/Todo.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/res/drawable/bg_calendar_date.xml
  app/src/main/res/drawable/bg_status.xml
  app/src/main/res/layout/activity_main.xml
Labels: Feature

#49 CreatePlanActivity 오늘 날짜 Decoration 기능 추가
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/res/drawable/bg_calendar_today.xml
Labels: Feature

#51 CreatePlanActivity Todo 추가
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanDialog.kt
Labels: Feature

#53 UI/string
  app/build.gradle
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/res/drawable/btn_back.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_create_plan.xml
  app/src/main/res/layout/activity_create_plan_dialog.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/activity_send_email.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_todo_main.xml
  app/src/main/res/layout/setting_detail.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#58 알람 액티비티 기능 구현 1차 PR
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/alarm/AlarmActivity.kt
  app/src/main/java/com/example/earlybirdy/data/Alarm.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/fragment_home.xml
Labels: Feature

#61 ui : 전반적인 layout 그라데이션 배경 작업
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_create_plan.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/setting_detail.xml
Labels: Design

#62 UI : SignupDialog, feature : SignupActivity
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupDialog.kt
  app/src/main/res/layout/activity_signup_dialog.xml
Labels: Design, Feature

#63 Feature/homefragment
  app/src/main/java/com/example/earlybirdy/alarm/AlarmActivity.kt
  app/src/main/java/com/example/earlybirdy/dto/UserDto.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/home/HomeViewModel.kt
  app/src/main/java/com/example/earlybirdy/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: Feature

#65 HomeFragment 알람 시간 적용
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
Labels: Feature

#68 ui : 앱 아이콘 변경 및 ManiFest에서 Splash Activity가 먼저 뜨게 변경
  app/src/main/AndroidManifest.xml
  app/src/main/ic_main-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main_round.xml
  app/src/main/res/mipmap-hdpi/ic_main.webp
  app/src/main/res/mipmap-hdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_main_round.webp
  app/src/main/res/mipmap-mdpi/ic_main.webp
  app/src/main/res/mipmap-mdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_main_round.webp
  app/src/main/res/mipmap-xhdpi/ic_main.webp
  app/src/main/res/mipmap-xhdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_main_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_main.webp
  app/src/main/res/mipmap-xxhdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_main_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main_round.webp
  app/src/main/res/values/ic_main_background.xml
Labels: Design

#69 feat : SettingActivity 알림설정 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#73 Feature/progress
  app/src/main/java/com/example/earlybirdy/data/MyGoal.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_todo_main.xml
Labels: Feature

#75 CreateTodoActivity Todo CRUD 구현
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanAdapter.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanDialog.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt
  app/src/main/res/layout/item_todo.xml
Labels: Feature

#77 feat : SettingActivity 로그아웃 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt
  build.gradle
Labels: Feature

#78 feature : Create, Update, Delete 데이터 베이스 연동
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanAdapter.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanDialog.kt
  app/src/main/java/com/example/earlybirdy/data/Todo.kt
Labels: Feature

#80 CreateTodoActivity 프론트엔드 상 Create / Delete / Update 버그 해결
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanAdapter.kt
  app/src/main/java/com/example/earlybirdy/data/Todo.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt
Labels: Feature

#83 CreateTodoActivity Firebase 데이터 로드 기능 구현
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/dto/TodoDto.kt
Labels: Feature

#84 마이페이지에서 localExp 값에 따라 경험치 량과 프로그레스 바, 레벨 값 변화
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: Feature

#88 Feature/progress
  app/build.gradle
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_todo_main.xml
  settings.gradle
Labels: Feature

#90 Create Todo 기능 수정 / 회원가입 시 경험치 추가
  app/src/main/java/com/example/earlybirdy/create_plan/CreateFailDialog.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanAdapter.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanDialog.kt
  app/src/main/java/com/example/earlybirdy/dto/UserDto.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/res/layout/activity_create_plan.xml
  app/src/main/res/layout/dialog_fail_to_add.xml
  app/src/main/res/layout/item_todo.xml
Labels: Fix, Feature

#92 Feat/profile
  app/src/main/java/com/example/earlybirdy/board/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/dto/UserDto.kt
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivityDialog.kt
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileDialog.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupDialog.kt
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_edit_profile_dialog.xml
  app/src/main/res/layout/activity_profile_dialog.xml
Labels: Feature

#93 알람 액티비티 타임피커의 시간에 따라 매일 반복되는 알람 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/alarm/AlarmActivity.kt
  app/src/main/java/com/example/earlybirdy/alarm/AlarmReceiver.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/main/SplashActivity.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/sendemail/SendEmailActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/res/layout/activity_create_plan.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: Fix, Feature

#94 Feature/percent
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/res/layout/item_todo_main.xml
Labels: Feature

#96 랭킹보드 작업을 위한 pr
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt
  app/src/main/res/drawable/btn_floating.png
  app/src/main/res/drawable/crown_bronze.png
  app/src/main/res/drawable/crown_gold.png
  app/src/main/res/drawable/crown_silver.png
  app/src/main/res/drawable/ic_1st_board_1.png
  app/src/main/res/drawable/ic_1st_board_crown.png
  app/src/main/res/drawable/ic_2nd_board.png
  app/src/main/res/drawable/ic_3rd_board.png
  app/src/main/res/drawable/ic_4th_board.png
  app/src/main/res/drawable/ic_5th_board.png
  app/src/main/res/drawable/ic_round_11.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_challenge.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_rangking.xml
  app/src/main/res/layout/item_challenge.xml
  app/src/main/res/layout/item_rangking.xml
  app/src/main/res/values/colors.xml
Labels: Design

#99 MyPageFragment 오류 수정 및 SettingDetail 오류 수정
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: Fix

#101 fix: EditProfileDialog, SignupDialog 프로필 사진 교체
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileDialog.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupDialog.kt
  app/src/main/res/drawable/img_profile_man1.png
  app/src/main/res/drawable/img_profile_man2.png
  app/src/main/res/drawable/img_profile_woman1.png
  app/src/main/res/drawable/img_profile_woman2.png
  app/src/main/res/layout/activity_profile_dialog.xml
  app/src/main/res/layout/activity_signup_dialog.xml
Labels: Fix

#103 MyPageFragment Firebase 연동하여 데이터 출력
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/dto/AttendanceDto.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: Feature

#106 feature: 가로모드,다크모드 막기
  app/src/main/AndroidManifest.xml
  app/src/main/res/values-night/themes.xml
Labels: Fix

#109 UI/rank
  app/src/main/java/com/example/RankingFragment.kt
  app/src/main/java/com/example/earlybirdy/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/res/layout/fragment_ranking.xml
  build.gradle
Labels: Design

#111 연결되지 않은 액티비티 및 프래그먼트 연결
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/res/layout/activity_create_plan.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: Feature

#113 Feature/rank
  app/src/main/java/com/example/RankingFragment.kt
  app/src/main/java/com/example/earlybirdy/RankingAdapter.kt
  app/src/main/java/com/example/earlybirdy/RankingFragment.kt
  app/src/main/java/com/example/earlybirdy/main/MainViewPagerAdapter.kt
  app/src/main/res/layout/fragment_ranking.xml
  app/src/main/res/layout/item_rangking.xml
Labels: Feature

#119 MyPageFragment Refactor
  app/src/main/java/com/example/earlybirdy/data/MyPageData.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragmentViewModel.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageViewModel.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageViewModelFactory.kt
  app/src/main/java/com/example/earlybirdy/my_page/UserRepository.kt
  app/src/main/java/com/example/earlybirdy/my_page/UserRepositoryImpl.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: Refactor, Fix

#120 refactor : MyPageFragment 추가 수정(intent, function 순서)
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: Refactor, Fix

#122 회원가입 얘외처
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/values/strings.xml
Labels: Fix, Feature

#125 타임피커의 시간이 7시가 되면 00분으로 분을 고정하는 기능 추가
  app/src/main/java/com/example/earlybirdy/alarm/AlarmActivity.kt
Labels: Feature

#128 Feat/setting
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/res/anim/exit.xml
  app/src/main/res/anim/horizon_enter.xml
  app/src/main/res/anim/horizon_exit.xml
  app/src/main/res/anim/none.xml
  app/src/main/res/anim/slide_left_enter.xml
  app/src/main/res/anim/slide_left_exit.xml
  app/src/main/res/anim/slide_right_enter.xml
  app/src/main/res/anim/slide_right_exit.xml
  app/src/main/res/anim/slide_up_enter.xml
  app/src/main/res/anim/slide_up_exit.xml
  app/src/main/res/anim/vertical_enter.xml
  app/src/main/res/anim/vertical_exit.xml
  app/src/main/res/drawable/btn_setting.xml
  app/src/main/res/layout/setting_detail.xml
  app/src/main/res/values/integers.xml
Labels: Feature

#129 Fix/rank
  app/src/main/java/com/example/earlybirdy/RankingAdapter.kt
  app/src/main/java/com/example/earlybirdy/RankingFragment.kt
  app/src/main/res/drawable/ic_tankback.png
  app/src/main/res/layout/fragment_ranking.xml
Labels: Fix

#134 MyPageFragment 수정
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageViewModel.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageViewModelFactory.kt
  app/src/main/java/com/example/earlybirdy/repository/UserRepository.kt
  app/src/main/java/com/example/earlybirdy/repository/UserRepositoryImpl.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt
  app/src/main/res/drawable/ic_edit_profile.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: Fix

#137 ui/설정 액티비티 고객지원 버튼 수정, 항목간격 수정
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/res/layout/activity_setting.xml
Labels: Design

#138 Fix/image
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileDialog.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupDialog.kt
  app/src/main/res/drawable/img_profile_sample.png
  app/src/main/res/layout/activity_edit_profile.xml
Labels: Fix

#139 로그인 액티비티 리펙토링
  app/build.gradle
  app/src/main/java/com/example/earlybirdy/sealedclass/SigninNavigation.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninViewModel.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
Labels: Refactor, Fix

#141 fix: 비밀번호 수정
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
Labels: Fix

#142 MyPageFragment MVVM live data 수정
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageViewModel.kt
Labels: Refactor

#143 Feature/profile
  app/src/main/java/com/example/earlybirdy/RankingFragment.kt
Labels: Feature

#145 SettingActivity 리팩토링 및 ViewModel 추가
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingCheckUserDialog.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingDeleteDialog.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingViewModel.kt
  app/src/main/java/com/example/earlybirdy/util/Constants.kt
  app/src/main/java/com/example/earlybirdy/util/IntentKeys.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
Labels: Refactor

#146 Fix/attend
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/res/drawable/img_profile_sample.png
Labels: Fix

#148 Feat/block
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/alarm/AlarmActivity.kt
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/example/earlybirdy/main/MainActivity.kt
  app/src/main/java/com/example/earlybirdy/main/NetworkChangeReceiver.kt
  app/src/main/java/com/example/earlybirdy/resetpassword/ResetPasswordActivity.kt
  app/src/main/java/com/example/earlybirdy/sendemail/SendEmailActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/res/drawable/img_profile_sample.png
Labels: Fix

#152 SendEmailActivity ViewModel 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/main/SplashActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/SignInActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/SignInViewModel.kt
  app/src/main/java/com/example/earlybirdy/signin/sendemail/SendEmailActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/sendemail/SendEmailViewModel.kt
  app/src/main/java/com/example/earlybirdy/util/IntentKeys.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_send_email.xml
  app/src/main/res/layout/activity_signin.xml
Labels: Refactor

#154 Fix/edit
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivityDialog.kt
  app/src/main/java/com/example/earlybirdy/resetpassword/ResetPasswordActivity.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_edit_profile.xml
Labels: Fix

#155 SendEmailActivity ViewModel 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/signin/sendemail/SendEmailActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/sendemail/SendEmailViewModel.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_send_email.xml
Labels: Refactor

#158 Design : ExpDialog
  app/src/main/java/com/example/earlybirdy/home/ExpDialog.kt
  app/src/main/res/drawable/ic_dialog_share.xml
  app/src/main/res/layout/dialog_exp.xml
Labels: Design

#160 중간 발표 전 수정 사항 확인
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_todo_main.xml
Labels: Design, Fix

#161 Fix : ExpDialog
  app/src/main/java/com/example/earlybirdy/home/ExpDialog.kt
  app/src/main/res/layout/dialog_exp.xml
Labels: Fix

#162 게시판 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/board/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/example/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/example/earlybirdy/data/BoardData.kt
  app/src/main/java/com/example/earlybirdy/dto/BoardDto.kt
  app/src/main/java/com/example/earlybirdy/dto/UserDto.kt
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/example/earlybirdy/main/MainActivity.kt
  app/src/main/java/com/example/earlybirdy/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/earlybirdy/resetpassword/ResetPasswordActivity.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_board_read.xml
  app/src/main/res/layout/activity_board_write.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/item_board.xml
  app/src/main/res/values/strings.xml
Labels: Design, Fix, Feature

#164 ui 목록 리스트화
  app/src/main/res/drawable/btn_setting.xml
  app/src/main/res/drawable/ic_listitem1.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_setting.xml
Labels: Design

#166 Fix/edit
  app/src/main/java/com/example/earlybirdy/signin/sendemail/SendEmailActivity.kt
  app/src/main/java/com/example/earlybirdy/signup/SignupActivity.kt
Labels: Fix

#170 Feature/custom
  app/src/main/java/com/example/earlybirdy/RankingFragment.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/res/drawable/bg_calendar_date1.xml
  app/src/main/res/drawable/bg_calendar_date2.xml
  app/src/main/res/drawable/bg_calendar_date3.xml
  app/src/main/res/drawable/bg_calendar_date4.xml
Labels: Feature

#173 피드백 내용 반영한 fix
  app/src/main/java/com/example/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/example/earlybirdy/main/MainActivity.kt
  app/src/main/java/com/example/earlybirdy/resetpassword/ResetPasswordActivity.kt
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_edit_profile_dialog.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/activity_signin.xml
Labels: Fix

#176 목표 리스트에 화살표 기능 추가
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/res/drawable/btn_leftarrow.xml
  app/src/main/res/drawable/btn_rightarrow.xml
  app/src/main/res/layout/fragment_home.xml
Labels: Feature

#178 [BoardActivity] 레이아웃 수정
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/example/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/res/drawable/btn_setting.xml
  app/src/main/res/drawable/ic_like.png
  app/src/main/res/drawable/ic_rank.png
  app/src/main/res/drawable/ic_reload.png
  app/src/main/res/layout/activity_board_read.xml
  app/src/main/res/layout/activity_board_write.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/fragment_challenge.xml
  app/src/main/res/layout/fragment_ranking.xml
  app/src/main/res/layout/item_board.xml
  app/src/main/res/layout/item_challenge.xml
Labels: Design
