Repository AndroidEarlyBirdy/EarlyBirdy, pull requests merged in 2023-11, with the labels that each got.

#180 커스텀 달력 background 수정
  app/src/main/java/com/example/earlybirdy/my_page/BackgroundSpan.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/res/drawable/bg_calendar_date1.xml
  app/src/main/res/drawable/bg_calendar_date2.xml
  app/src/main/res/drawable/bg_calendar_date3.xml
  app/src/main/res/drawable/bg_calendar_date4.xml
  app/src/main/res/values/colors.xml
Labels: Feature

#182 [Board Fragment]게시판 기능 구현
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/example/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/example/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_board_read.xml
  app/src/main/res/layout/activity_board_write.xml
  app/src/main/res/layout/item_board.xml
Labels: Design, Fix, Feature

#186 [Homefragment] 명언 및 날씨 api 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/earlybirdy/RankingFragment.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/home/WeatherData.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/res/drawable/ic_glassbackground.xml
  app/src/main/res/drawable/ic_topbackground.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#187 마이 프레그먼트 오류 수정 및 상단 명언 구현
  app/src/main/java/com/example/earlybirdy/RankingFragment.kt
  app/src/main/java/com/example/earlybirdy/dto/AttendanceDto.kt
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/home/WeatherData.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
Labels: Fix, Feature

#188 [BoardFragment] 게시판 추가 기능 구현
  app/build.gradle
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/example/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/example/earlybirdy/dto/BoardDto.kt
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/res/layout/activity_board_read.xml
  app/src/main/res/layout/activity_board_write.xml
  app/src/main/res/layout/item_board.xml
Labels: Fix, Feature

#190 [CreatePlanActivity] Plan 삭제 시 경험치 삭제 구현
  app/src/main/java/com/example/earlybirdy/create_plan/CreatePlanActivity.kt
Labels: Feature

#193 [Profile]프로필 이미지추가
  app/src/main/java/com/example/earlybirdy/setting/SettingDetailActivity.kt
  app/src/main/res/drawable/ic_person1.png
  app/src/main/res/drawable/ic_person2.png
  app/src/main/res/drawable/ic_person3.png
  app/src/main/res/drawable/ic_person4.png
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_edit_profile_dialog.xml
  app/src/main/res/layout/activity_profile_dialog.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/activity_setting_delete_dialog.xml
  app/src/main/res/layout/activity_setting_login_dialog.xml
  app/src/main/res/layout/activity_signup_dialog.xml
  app/src/main/res/layout/dialog_exp.xml
  app/src/main/res/layout/dialog_fail_to_add.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_ranking.xml
  app/src/main/res/layout/item_challenge.xml
  app/src/main/res/layout/item_rangking.xml
  app/src/main/res/values/strings.xml
Labels: Design

#195 [Home-Fragment] 날씨 api 오류 수정
  app/src/main/java/com/example/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/example/earlybirdy/home/WeatherData.kt
  app/src/main/res/drawable/ic_cloud.xml
  app/src/main/res/drawable/ic_mist.xml
  app/src/main/res/drawable/ic_none.xml
  app/src/main/res/drawable/ic_partly_cloudy.xml
  app/src/main/res/drawable/ic_rainy.xml
  app/src/main/res/drawable/ic_rainy_heavy.xml
  app/src/main/res/drawable/ic_rainy_light.xml
  app/src/main/res/drawable/ic_snow.xml
  app/src/main/res/drawable/ic_sunny.xml
  app/src/main/res/drawable/ic_thunderstorm.xml
  app/src/main/res/layout/fragment_home.xml
  build.gradle
  gradle.properties
Labels: Fix

#197 달력 색상 오류 수정
  app/src/main/java/com/example/earlybirdy/my_page/MyPageFragment.kt
Labels: Fix

#201 Feat/reply
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/example/earlybirdy/board/board_read/CommentAdapter.kt
  app/src/main/java/com/example/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/example/earlybirdy/dto/CommentDto.kt
  app/src/main/res/layout/activity_board_read.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/item_board.xml
  app/src/main/res/layout/item_board_comment.xml
Labels: Design, Fix, Feature

#204 [Board] Firebase Storage 활용 사진 업로드, 다운로드 구현
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardFragment.kt
  app/src/main/java/com/example/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/example/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/example/earlybirdy/dto/BoardDto.kt
  app/src/main/res/values/strings.xml
Labels: Feature

#206 알림 및 기타 기능 수정
  app/src/main/java/com/example/earlybirdy/alarm/AlarmActivity.kt
  app/src/main/java/com/example/earlybirdy/alarm/AlarmReceiver.kt
  app/src/main/java/com/example/earlybirdy/main/SplashActivity.kt
  app/src/main/java/com/example/earlybirdy/sealedclass/SigninNavigation.kt
  app/src/main/java/com/example/earlybirdy/setting/SettingCheckUserDialog.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/example/earlybirdy/signin/SigninViewModel.kt
Labels: Fix

#208 Board 사진 업로드 기능 구현
  app/src/main/java/com/example/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/example/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/example/earlybirdy/board/board_write/BoardWriteActivity.kt
Labels: Feature

#210 라이선스, 약관 구글폼 연동
  app/src/main/java/com/example/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/example/earlybirdy/util/Constants.kt
Labels: Feature

#212 Feat/noti
  app/build.gradle
  app/src/main/java/com/nbcproject/earlybirdy/RankingAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/AlarmDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/HomeViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/main/MainActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/main/SplashActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/resetpassword/ResetPasswordActivity.kt
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/dialog_alarm.xml
Labels: Design, Fix, Feature

#214 회원탈퇴 오류 수정
  app/src/main/java/com/nbcproject/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/SettingCheckUserDialog.kt
Labels: Fix

#219 게시판에서 내글보기랑 전체글보기에서 새로고침 버튼을 눌렀을 때 무조건 내글보기로 가는 문제 수정
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardFragment.kt
Labels: Fix

#221 [SettingActivty] Refactor
  app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepository.kt
  app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingCheckUserDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingDeleteDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/viewmodel/SettingViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/viewmodel/SettingViewModelFactory.kt
  app/src/main/res/values/strings.xml
Labels: Refactor

#222 [SettingDetailActivity] Refactor
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcproject/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/SettingDetailActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/setting_detail.xml
Labels: Refactor

#225 프로필 사진 변경 및 프로필 사진 오류 해결
  app/src/main/java/com/nbcproject/earlybirdy/RankingFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/ExpDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/main/MainActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/main/MainViewPagerAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingCheckUserDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/signup/SignupActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/signup/SignupDialog.kt
  app/src/main/res/anim/exit.xml
  app/src/main/res/anim/horizon_enter.xml
  app/src/main/res/anim/horizon_exit.xml
  app/src/main/res/anim/none.xml
  app/src/main/res/anim/slide_left_enter.xml
  app/src/main/res/anim/slide_left_exit.xml
  app/src/main/res/anim/slide_right_enter.xml
  app/src/main/res/anim/slide_right_exit.xml
  app/src/main/res/anim/slide_up_enter.xml
  app/src/main/res/anim/slide_up_exit.xml
  app/src/main/res/anim/vertical_enter.xml
  app/src/main/res/anim/vertical_exit.xml
  app/src/main/res/drawable/ic_question_mark.xml
  app/src/main/res/layout/activity_profile_dialog.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/activity_signup_dialog.xml
  app/src/main/res/layout/dialog_exp.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: Fix

#229 [SettingCheckUserDialog] MVVM 패턴 적용
  app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepository.kt
  app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcproject/earlybirdy/repository/UserRepository.kt
  app/src/main/java/com/nbcproject/earlybirdy/repository/UserRepositoryImpl.kt
  app/src/main/java/com/nbcproject/earlybirdy/sealedclass/CheckAuth.kt
  app/src/main/java/com/nbcproject/earlybirdy/sealedclass/CheckDelete.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingCheckUserDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingDeleteDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/viewmodel/SettingViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/viewmodel/SettingViewModelFactory.kt
  app/src/main/res/values/strings.xml
Labels: Refactor

#231 전체 페이지 ui 수정 작업
  app/build.gradle
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivityDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingDeleteDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/signin/SigninActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/signin/sendemail/SendEmailActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/signup/SignupActivity.kt
  app/src/main/res/drawable/btn_back.xml
  app/src/main/res/drawable/dialog_edittext_background.xml
  app/src/main/res/drawable/dialog_radius_background.xml
  app/src/main/res/drawable/ic_create_plan_delete.xml
  app/src/main/res/drawable/ic_dialog_item.xml
  app/src/main/res/drawable/ic_question_mark.xml
  app/src/main/res/drawable/ic_rank_back.xml
  app/src/main/res/drawable/selector_switch.xml
  app/src/main/res/drawable/selector_thumb.xml
  app/src/main/res/drawable/switch_thumb_off.xml
  app/src/main/res/drawable/switch_thumb_on.xml
  app/src/main/res/drawable/switch_track_off.xml
  app/src/main/res/drawable/switch_track_on.xml
  app/src/main/res/layout/activity_create_plan.xml
  app/src/main/res/layout/activity_create_plan_dialog.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_edit_profile_dialog.xml
  app/src/main/res/layout/activity_profile_dialog.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/activity_send_email.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_setting_delete_dialog.xml
  app/src/main/res/layout/activity_setting_login_dialog.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/activity_signup_dialog.xml
  app/src/main/res/layout/dialog_alarm.xml
  app/src/main/res/layout/dialog_fail_to_add.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_ranking.xml
  app/src/main/res/layout/item_todo.xml
  app/src/main/res/layout/item_todo_main.xml
  app/src/main/res/values/dialog_container_style.xml
  app/src/main/res/values/strings.xml
Labels: Fix

#232 SendEmailActivity 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcproject/earlybirdy/main/SplashActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepository.kt
  app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/sendemail/SendEmailActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/sendemail/viewmodel/SendEmailViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/sendemail/viewmodel/SendEmailViewModelFactory.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signin/SigninActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signin/viewmodel/SigninViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/signin/sendemail/SendEmailViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_send_email.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
Labels: Refactor

#236 게시글 보기 페이지 신고하기 기능 추가
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/util/Constants.kt
  app/src/main/res/layout/activity_board_read.xml
Labels: Feature

#238 [SiginInActivity] 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/main/SplashActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepository.kt
  app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcproject/earlybirdy/repository/UserRepositoryImpl.kt
  app/src/main/java/com/nbcproject/earlybirdy/resetpassword/ResetPasswordActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/sealedclass/CheckDelete.kt
  app/src/main/java/com/nbcproject/earlybirdy/sealedclass/SignInNavigation.kt
  app/src/main/java/com/nbcproject/earlybirdy/sealedclass/SigninNavigation.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingCheckUserDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signin/SignInActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signin/viewmodel/SignInViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signin/viewmodel/SignInViewModelFactory.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signin/viewmodel/SigninViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/values/strings.xml
Labels: Refactor

#241 Fix/전 액티비티 가로모드 확인
  app/src/main/AndroidManifest.xml
Labels: Fix

#243 [AndroidManifest] AndroidManifest 오류 Fix
  app/src/main/AndroidManifest.xml
Labels: Fix

#244 게시판 레이아웃 수정 및 추가 기능 수정
  app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupActivity.kt
  app/src/main/res/layout/activity_board_read.xml
  app/src/main/res/layout/activity_board_write.xml
  app/src/main/res/layout/activity_setting_login_dialog.xml
Labels: Design, Fix

#245 ResetPassword 리팩토링
  app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepository.kt
  app/src/main/java/com/nbcproject/earlybirdy/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcproject/earlybirdy/resetpassword/ResetPasswordActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/resetpassword/viewmodel/ResetPasswordViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/resetpassword/viewmodel/ResetPasswordViewModelFactory.kt
  app/src/main/java/com/nbcproject/earlybirdy/sealedclass/CheckAuth.kt
  app/src/main/java/com/nbcproject/earlybirdy/sealedclass/CheckChangePassword.kt
  app/src/main/java/com/nbcproject/earlybirdy/sealedclass/SignInNavigation.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingCheckUserDialog.kt
  app/src/main/res/layout/activity_edit_profile_dialog.xml
  app/src/main/res/values/strings.xml
Labels: Refactor

#247 메인보드 ui 수정
  app/src/main/res/drawable/ic_board_list.png
  app/src/main/res/drawable/ic_comment.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/item_board.xml
Labels: Refactor

#250 프로그레스바 ui 수정
  app/src/main/res/layout/fragment_home.xml
Labels: Refactor

#252 [BoardFragment] 댓글 수 출력 기능 구현
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupActivity.kt
Labels: Feature

#253 ExpDialog 기능, UI 수정 및 이미지 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/ExpDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupActivity.kt
  app/src/main/res/drawable/exp_background.png
  app/src/main/res/drawable/exp_dialog_button.xml
  app/src/main/res/drawable/ic_person1.png
  app/src/main/res/drawable/ic_person2.png
  app/src/main/res/drawable/ic_person3.png
  app/src/main/res/drawable/ic_person4.png
  app/src/main/res/layout/dialog_exp.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/xml/filepaths.xml
Labels: Design, Fix

#255 인터넷 Dialog 수정 및 기본 프로필 사진 변경
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/main/MainActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/activity_signup_dialog.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: Fix

#258 랭킹보드 ui 최종 수정
  app/src/main/java/com/nbcproject/earlybirdy/RankingFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/main/MainActivity.kt
  app/src/main/res/drawable/ic_1.xml
  app/src/main/res/drawable/ic_2.xml
  app/src/main/res/drawable/ic_3.xml
  app/src/main/res/drawable/ic_rectangle.xml
  app/src/main/res/drawable/ic_row.png
  app/src/main/res/layout/fragment_ranking.xml
  app/src/main/res/layout/item_rangking.xml
Labels: Refactor

#260 추가 수정 및 게시판 수정
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/dto/BoardDto.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/dialog/SettingCheckUserDialog.kt
  app/src/main/res/layout/activity_board_read.xml
  app/src/main/res/layout/activity_board_write.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/item_board.xml
  app/src/main/res/layout/item_board_comment.xml
  app/src/main/res/values/style.xml
Labels: Design, Fix

#262 게시글 사진이 없을 때 대체 이미지 대표로고로 수정
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
Labels: Design

#263 exp 다이얼로그 ui 수정
  app/build.gradle
  app/src/main/java/com/nbcproject/earlybirdy/home/ExpDialog.kt
  app/src/main/res/layout/dialog_exp.xml
  app/src/main/res/raw/lottie.json
Labels: Refactor

#268 SettingActivity 추가 수정 사항 반영
  app/src/main/java/com/nbcproject/earlybirdy/setting/SettingActivity.kt
Labels: Refactor

#271 SendEmailActivity 재 Refactoring
  app/src/main/java/com/nbcproject/earlybirdy/sign/sendemail/SendEmailActivity.kt
Labels: Refactor

#273 Signup Activity 및 Dialog 리팩토링
  app/src/main/java/com/nbcproject/earlybirdy/resetpassword/ResetPasswordActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupDialog.kt
  app/src/main/res/drawable/img_profile_man1.png
  app/src/main/res/drawable/img_profile_man2.png
  app/src/main/res/drawable/img_profile_woman1.png
  app/src/main/res/drawable/img_profile_woman2.png
  app/src/main/res/values/strings.xml
Labels: Refactor

#275 Alarm Dialog 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcproject/earlybirdy/alarm/AlarmActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/alarm/AlarmDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/alarm/AlarmReceiver.kt
  app/src/main/java/com/nbcproject/earlybirdy/util/SharedPreferenceKeys.kt
  app/src/main/java/com/nbcproject/earlybirdy/util/UtilFunction.kt
  app/src/main/res/layout/activity_alarm.xml
Labels: Refactor

#276 Data Class 및 DTO 정리
  app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/data/Alarm.kt
  app/src/main/java/com/nbcproject/earlybirdy/data/BoardData.kt
Labels: Remove

#278 BoardFragment, 관련 Activity 리팩토링
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/CommentAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/res/values/strings.xml
Labels: Refactor

#279 프로젝트 리팩토링
  app/src/main/java/com/nbcproject/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/create_plan/CreatePlanDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivityDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/ExpDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/HomeViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/WeatherData.kt
  app/src/main/java/com/nbcproject/earlybirdy/main/MainViewPagerAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/ranking/RankingAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/ranking/RankingFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/resetpassword/ResetPasswordActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/setting/SettingActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/util/Constants.kt
  app/src/main/java/com/nbcproject/earlybirdy/util/IntentKeys.kt
  app/src/main/res/values/strings.xml
Labels: Refactor

#281 UI/fixui
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/CommentAdapter.kt
  app/src/main/res/layout/activity_create_plan_dialog.xml
  app/src/main/res/layout/activity_edit_profile_dialog.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/activity_send_email.xml
  app/src/main/res/layout/activity_setting_delete_dialog.xml
  app/src/main/res/layout/activity_setting_login_dialog.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/dialog_fail_to_add.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: Design, Fix

#287 Hoem Fragment Nullpoint Exception 해결
  app/src/main/java/com/nbcproject/earlybirdy/create_plan/CreatePlanActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/create_plan/dialog/CreateFailDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/create_plan/dialog/CreatePlanDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/dialog/EditProfileActivityDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/dialog/EditProfileDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/HomeFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/my_page/MyPageFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/my_page/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nbcproject/earlybirdy/my_page/viewmodel/MyPageViewModelFactory.kt
  app/src/main/java/com/nbcproject/earlybirdy/resetpassword/ResetPasswordActivity.kt
Labels: Fix

#289 기본 프로필 이미지 수정
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/ranking/RankingFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/signup/SignupActivity.kt
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_ranking.xml
  app/src/main/res/layout/item_challenge.xml
  app/src/main/res/layout/item_rangking.xml
Labels: Fix

#291 EdtiProfile 에서 비밀번호 수정 시 빈칸 입력 시 오류 문제 해결
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/EditProfileActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/dialog/EditProfileActivityDialog.kt
  app/src/main/java/com/nbcproject/earlybirdy/resetpassword/ResetPasswordActivity.kt
Labels: Fix

#297 SendEmailActivity 이메일 입력 공백 시 발생 문제 해결 / Board 작성 시 버튼 여러 번 클릭 시 글 중복 생성 문제 해결
  app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/sign/sendemail/SendEmailActivity.kt
Labels: Fix

#299 게시판 ui 최종 수정
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/edit_profile/dialog/EditProfileDialog.kt
  app/src/main/res/drawable/btn_add_photo.xml
  app/src/main/res/drawable/btn_delete.xml
  app/src/main/res/drawable/btn_modify.xml
  app/src/main/res/drawable/btn_more.xml
  app/src/main/res/drawable/ic_no_photos.xml
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/drawable/ic_user.png
  app/src/main/res/layout/activity_board_read.xml
  app/src/main/res/layout/activity_board_write.xml
  app/src/main/res/layout/dialog_option.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/item_board_comment.xml
Labels: Refactor

#301 Fix/string
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardFragment.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/CommentAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_write/BoardWriteActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/dto/BoardDto.kt
  app/src/main/res/layout/activity_board_read.xml
Labels: Design, Fix, Feature

#308 전체 코드 전검 및 drawable 파일 일부 정리
  app/src/main/java/com/nbcproject/earlybirdy/home/alarm/AlarmReceiver.kt
  app/src/main/java/com/nbcproject/earlybirdy/ranking/RankingFragment.kt
  app/src/main/res/drawable/bg_calendar_date.xml
  app/src/main/res/drawable/bg_line.xml
  app/src/main/res/drawable/btn_delete.xml
  app/src/main/res/drawable/btn_floating.png
  app/src/main/res/drawable/btn_modify.xml
  app/src/main/res/drawable/btn_setting.xml
  app/src/main/res/drawable/crown_bronze.png
  app/src/main/res/drawable/crown_gold.png
  app/src/main/res/drawable/crown_silver.png
  app/src/main/res/drawable/exp_background.png
  app/src/main/res/drawable/ic_1st_board_1.png
  app/src/main/res/drawable/ic_2nd_board.png
  app/src/main/res/drawable/ic_3rd_board.png
  app/src/main/res/drawable/ic_4th_board.png
  app/src/main/res/drawable/ic_board_fill.xml
  app/src/main/res/drawable/ic_dialog_share.xml
  app/src/main/res/drawable/ic_home_fill.xml
  app/src/main/res/drawable/ic_like.png
  app/src/main/res/drawable/ic_line.xml
  app/src/main/res/drawable/ic_list_background.xml
  app/src/main/res/drawable/ic_mypage_fill.xml
  app/src/main/res/drawable/ic_rank_back.xml
  app/src/main/res/drawable/ic_rectangle.xml
  app/src/main/res/drawable/ic_round_11.xml
  app/src/main/res/drawable/ic_roundingbox.xml
  app/src/main/res/drawable/ic_tankback.png
  app/src/main/res/drawable/ic_topbackground.xml
  app/src/main/res/drawable/img_profile_add111.png
  app/src/main/res/drawable/img_profile_eye.xml
  app/src/main/res/drawable/img_profile_openeye.xml
  app/src/main/res/layout/activity_board_read.xml
  app/src/main/res/layout/activity_create_plan.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_send_email.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_exp.xml
  app/src/main/res/layout/dialog_fail_to_add.xml
  app/src/main/res/layout/dialog_option.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_ranking.xml
  app/src/main/res/layout/item_board_comment.xml
Labels: Fix, Remove

#311 Board 댓글 작성 시 즉시 반영
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
Labels: Fix

#312 1116 MainBackup
  README.md
  app/build.gradle
  app/src/main/java/com/nbcproject/earlybirdy/board/board_read/BoardReadActivity.kt
  app/src/main/java/com/nbcproject/earlybirdy/home/alarm/AlarmReceiver.kt
  app/src/main/java/com/nbcproject/earlybirdy/ranking/RankingFragment.kt
  app/src/main/res/drawable/bg_calendar_date.xml
  app/src/main/res/drawable/bg_line.xml
  app/src/main/res/drawable/btn_delete.xml
  app/src/main/res/drawable/btn_floating.png
  app/src/main/res/drawable/btn_modify.xml
  app/src/main/res/drawable/btn_setting.xml
  app/src/main/res/drawable/crown_bronze.png
  app/src/main/res/drawable/crown_gold.png
  app/src/main/res/drawable/crown_silver.png
  app/src/main/res/drawable/exp_background.png
  app/src/main/res/drawable/ic_1st_board_1.png
  app/src/main/res/drawable/ic_2nd_board.png
  app/src/main/res/drawable/ic_3rd_board.png
  app/src/main/res/drawable/ic_4th_board.png
  app/src/main/res/drawable/ic_board_fill.xml
  app/src/main/res/drawable/ic_dialog_share.xml
  app/src/main/res/drawable/ic_home_fill.xml
  app/src/main/res/drawable/ic_like.png
  app/src/main/res/drawable/ic_line.xml
  app/src/main/res/drawable/ic_list_background.xml
  app/src/main/res/drawable/ic_mypage_fill.xml
  app/src/main/res/drawable/ic_rank_back.xml
  app/src/main/res/drawable/ic_rectangle.xml
  app/src/main/res/drawable/ic_round_11.xml
  app/src/main/res/drawable/ic_roundingbox.xml
  app/src/main/res/drawable/ic_tankback.png
  app/src/main/res/drawable/ic_topbackground.xml
  app/src/main/res/drawable/img_profile_add111.png
  app/src/main/res/drawable/img_profile_eye.xml
  app/src/main/res/drawable/img_profile_openeye.xml
  app/src/main/res/layout/activity_board_read.xml
  app/src/main/res/layout/activity_create_plan.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_send_email.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_exp.xml
  app/src/main/res/layout/dialog_fail_to_add.xml
  app/src/main/res/layout/dialog_option.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_ranking.xml
  app/src/main/res/layout/item_board_comment.xml
Labels: Backup

#315 게시글 수정
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardAdapter.kt
  app/src/main/java/com/nbcproject/earlybirdy/board/board_main/BoardFragment.kt
Labels: Fix
